<a href="https://colab.research.google.com/github/BiancadeFrancisco/gbr_tunned_houses/blob/main/PR%C3%81TICA_OTIMIZA%C3%87%C3%83O_HIPERPAR%C3%A2METRO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# APÓS PREVER O PREÇO DE CASAS, VOCÊS IMPLEMENTARÃO O GRIDSEARCH NO MODELO DE GRADIENTBOOSTING PARA TENTAR MELHORAR A PERFORMANCE DO MODELO AUMENTANDO O R² E DIMINUINDO O MAE:

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
casa = pd.read_excel("/content/house.xlsx")

casa.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,ExterQual,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,Gd,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,TA,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,Gd,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,TA,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,Gd,...,192,84,0,0,0,0,0,12,2008,250000

In [ ]:
# TRANSFORMAR VARIÁVEIS COMPOSTAS EM DUMMIES:

casa = pd.get_dummies(casa)

casa.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SalePrice,ExterQual_Ex,ExterQual_Fa,ExterQual_Gd,ExterQual_TA,ExterCond_Ex,ExterCond_Fa,ExterCond_Gd,ExterCond_Po,ExterCond_TA
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,208500,0,0,1,0,0,0,0,0,1
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,181500,0,0,0,1,0,0,0,0,1
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,223500,0,0,1,0,0,0,0,0,1
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,140000,0,0,0,1,0,0,0,0,1
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,250000,0,0,1,0,0,0,0,0,1

In [ ]:
casa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 47 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   OverallQual    1460 non-null   int64
 5   OverallCond    1460 non-null   int64
 6   YearBuilt      1460 non-null   int64
 7   YearRemodAdd   1460 non-null   int64
 8   MasVnrArea     1452 non-null   float64
 9   BsmtFinSF1     1460 non-null   int64
 10  BsmtFinSF2     1460 non-null   int64
 11  BsmtUnfSF      1460 non-null   int64
 12  TotalBsmtSF    1460 non-null   int64
 13  1stFlrSF       1460 non-null   int64
 14  2ndFlrSF       1460 non-null   int64
 15  LowQualFinSF   1460 non-null   int64
 16  GrLivArea      1460 non-null   int64
 17  BsmtFullBath   1460 non-null   int64
 18  BsmtHalfBath   1460 non-null   int64
 19  FullBath       1460 non-null   int64
 20  HalfBath       1460 non-null   int64
 21  BedroomAbvGr   1460 non-null   int64
 22  KitchenAbvGr   1460 non-null   int64
 23  TotRmsAbvGrd   1460 non-null   int64
 24  Fireplaces     1460 non-null   int64
 25  GarageYrBlt    1379 non-null   float64
 26  GarageCars     1460 non-null   int64
 27  GarageArea     1460 non-null   int64
 28  WoodDeckSF     1460 non-null   int64
 29  OpenPorchSF    1460 non-null   int64
 30  EnclosedPorch  1460 non-null   int64
 31  3SsnPorch      1460 non-null   int64
 32  ScreenPorch    1460 non-null   int64
 33  PoolArea       1460 non-null   int64
 34  MiscVal        1460 non-null   int64
 35  MoSold         1460 non-null   int64
 36  YrSold         1460 non-null   int64
 37  SalePrice      1460 non-null   int64
 38  ExterQual_Ex   1460 non-null   uint8
 39  ExterQual_Fa   1460 non-null   uint8
 40  ExterQual_Gd   1460 non-null   uint8
 41  ExterQual_TA   1460 non-null   uint8
 42  ExterCond_Ex   1460 non-null   uint8
 43  ExterCond_Fa   1460 non-null   uint8
 44  ExterCond_Gd   1460 non-null   uint8
 45  ExterCond_Po   1460 non-null   uint8
 46  ExterCond_TA   1460 non-null   uint8
dtypes: float64(3), int64(35), uint8(9)
memory usage: 446.4 KB

In [ ]:
# EXCLUIR DADOS NULOS:

casa = casa.dropna()

In [ ]:
casa.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1121 entries, 0 to 1459
Data columns (total 47 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1121 non-null   int64
 1   MSSubClass     1121 non-null   int64
 2   LotFrontage    1121 non-null   float64
 3   LotArea        1121 non-null   int64
 4   OverallQual    1121 non-null   int64
 5   OverallCond    1121 non-null   int64
 6   YearBuilt      1121 non-null   int64
 7   YearRemodAdd   1121 non-null   int64
 8   MasVnrArea     1121 non-null   float64
 9   BsmtFinSF1     1121 non-null   int64
 10  BsmtFinSF2     1121 non-null   int64
 11  BsmtUnfSF      1121 non-null   int64
 12  TotalBsmtSF    1121 non-null   int64
 13  1stFlrSF       1121 non-null   int64
 14  2ndFlrSF       1121 non-null   int64
 15  LowQualFinSF   1121 non-null   int64
 16  GrLivArea      1121 non-null   int64
 17  BsmtFullBath   1121 non-null   int64
 18  BsmtHalfBath   1121 non-null   int64
 19  FullBath       1121 non-null   int64
 20  HalfBath       1121 non-null   int64
 21  BedroomAbvGr   1121 non-null   int64
 22  KitchenAbvGr   1121 non-null   int64
 23  TotRmsAbvGrd   1121 non-null   int64
 24  Fireplaces     1121 non-null   int64
 25  GarageYrBlt    1121 non-null   float64
 26  GarageCars     1121 non-null   int64
 27  GarageArea     1121 non-null   int64
 28  WoodDeckSF     1121 non-null   int64
 29  OpenPorchSF    1121 non-null   int64
 30  EnclosedPorch  1121 non-null   int64
 31  3SsnPorch      1121 non-null   int64
 32  ScreenPorch    1121 non-null   int64
 33  PoolArea       1121 non-null   int64
 34  MiscVal        1121 non-null   int64
 35  MoSold         1121 non-null   int64
 36  YrSold         1121 non-null   int64
 37  SalePrice      1121 non-null   int64
 38  ExterQual_Ex   1121 non-null   uint8
 39  ExterQual_Fa   1121 non-null   uint8
 40  ExterQual_Gd   1121 non-null   uint8
 41  ExterQual_TA   1121 non-null   uint8
 42  ExterCond_Ex   1121 non-null   uint8
 43  ExterCond_Fa   1121 non-null   uint8
 44  ExterCond_Gd   1121 non-null   uint8
 45  ExterCond_Po   1121 non-null   uint8
 46  ExterCond_TA   1121 non-null   uint8
dtypes: float64(3), int64(35), uint8(9)
memory usage: 351.4 KB

In [ ]:
casa.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SalePrice,ExterQual_Ex,ExterQual_Fa,ExterQual_Gd,ExterQual_TA,ExterCond_Ex,ExterCond_Fa,ExterCond_Gd,ExterCond_Po,ExterCond_TA
count,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,...,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.0,1121.000000
mean,726.842105,56.146298,70.665477,10122.956289,6.212310,5.561106,1972.264942,1985.683318,108.487957,438.399643,...,185506.152542,0.041035,0.006244,0.355040,0.597681,0.001784,0.015165,0.092774,0.0,0.890277
std,420.769012,41.772684,24.266812,8129.302641,1.380822,1.068236,30.967730,21.025974,189.500966,468.385038,...,82999.159004,0.198459,0.078810,0.478739,0.490585,0.042220,0.122264,0.290245,0.0,0.312684
min,1.000000,20.000000,21.000000,1300.000000,2.000000,2.000000,1880.000000,1950.000000,0.000000,0.000000,...,35311.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,364.000000,20.000000,60.000000,7590.000000,5.000000,5.000000,1953.000000,1966.000000,0.000000,0.000000,...,131000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.000000
50%,725.000000,50.000000,70.000000,9416.000000,6.000000,5.000000,1974.000000,1995.000000,0.000000,374.000000,...,164900.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.0,1.000000
75%,1091.000000,70.000000,80.000000,11361.000000,7.000000,6.000000,2003.000000,2005.000000,170.000000,702.000000,...,219500.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,1.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,755000.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000

In [ ]:
# COLOCAR OS DADOS EM ESCALAS PRÓXIMAS:

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

casa_normal = pd.DataFrame(scaler.fit_transform(casa), index=casa.index, columns=casa.columns)

casa_normal.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SalePrice,ExterQual_Ex,ExterQual_Fa,ExterQual_Gd,ExterQual_TA,ExterCond_Ex,ExterCond_Fa,ExterCond_Gd,ExterCond_Po,ExterCond_TA
0,0.000000,0.235294,0.150685,0.033420,0.625,0.428571,0.946154,0.883333,0.12250,0.125089,...,0.240644,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.000685,0.000000,0.202055,0.038795,0.500,0.857143,0.738462,0.433333,0.00000,0.173281,...,0.203128,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,0.001371,0.235294,0.160959,0.046507,0.625,0.428571,0.930769,0.866667,0.10125,0.086109,...,0.261487,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.002056,0.294118,0.133562,0.038561,0.625,0.428571,0.269231,0.333333,0.00000,0.038271,...,0.145464,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,0.002742,0.235294,0.215753,0.060576,0.750,0.428571,0.923077,0.833333,0.21875,0.116052,...,0.298308,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
# CRIAR AS VARIÁVEIS Y E X

# Labels are the values we want to predict
labels = np.array(casa_normal['SalePrice'])
# Remove the labels from the features
# axis 1 refers to the columns
features= casa_normal.drop('SalePrice', axis = 1)
# Saving feature names for later use
feature_list = list(features.columns)
# Convert to numpy array
features = np.array(features)

In [ ]:
# TREINO E TESTE:

# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

In [ ]:
from sklearn.datasets import make_moons
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor,GradientBoostingRegressor
from sklearn import metrics

In [ ]:
# TREINAR NOSSO MODELO COM O GRADIENT BOOSTING:

# 1° MODELO LINEAR REGULAR

grb = GradientBoostingRegressor(n_estimators=100)
grb.fit(train_features, train_labels)
gbr_pred = grb.predict(test_features)

In [ ]:
# Calculate the absolute errors
errors_gbr = abs(gbr_pred - test_labels)

# Print out the mean absolute error (mae)
r_sq = grb.score(test_features, test_labels)
print('Coeficiente de Determinação (R²):', r_sq)

print('MAE:', metrics.mean_absolute_error(test_labels, gbr_pred))
print('MSE:', metrics.mean_squared_error(test_labels, gbr_pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(test_labels, gbr_pred)))

Coeficiente de Determinação (R²): 0.8873389716932708
MAE: 0.025870298857563853
MSE: 0.0017662912096296666
RMSE: 0.042027267453757525

In [ ]:
# UTILIZAR O GRID PARA MELHORAR ESSES PARAMETROS:

from sklearn.model_selection import GridSearchCV


parameters = {'learning_rate': [0.03],
                  'subsample'    : [0.2],
                  'n_estimators' : [100,500,1000, 1500],
                  'max_depth'    : [8]
                 }

grid_search = GridSearchCV(grb, parameters, scoring='r2', cv=2, n_jobs=-1)

In [ ]:
grid_search.fit(train_features, train_labels)

GridSearchCV(cv=2, estimator=GradientBoostingRegressor(), n_jobs=-1,
             param_grid={'learning_rate': [0.03], 'max_depth': [8],
                         'n_estimators': [100, 500, 1000, 1500],
                         'subsample': [0.2]},
             scoring='r2')

In [ ]:
    print(" Results from Grid Search " )
    print("\n The best estimator across ALL searched params:\n",grid_search.best_estimator_)
    print("\n The best score across ALL searched params:\n",grid_search.best_score_)
    print("\n The best parameters across ALL searched params:\n",grid_search.best_params_)

 Results from Grid Search

 The best estimator across ALL searched params:
 GradientBoostingRegressor(learning_rate=0.03, max_depth=8, n_estimators=500,
                          subsample=0.2)

 The best score across ALL searched params:
 0.8422269484410947

 The best parameters across ALL searched params:
 {'learning_rate': 0.03, 'max_depth': 8, 'n_estimators': 500, 'subsample': 0.2}

In [ ]:
best_model = grid_search.best_estimator_

In [ ]:
best_model.get_params()

{'alpha': 0.9,
 'ccp_alpha': 0.0,
 'criterion': 'friedman_mse',
 'init': None,
 'learning_rate': 0.03,
 'loss': 'squared_error',
 'max_depth': 8,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 500,
 'n_iter_no_change': None,
 'random_state': None,
 'subsample': 0.2,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [ ]:
grb_tunned = GradientBoostingRegressor(alpha = 0.9,  ccp_alpha = 0.0,
 criterion = 'friedman_mse',
 init = None,
 learning_rate = 0.03,
 loss = 'squared_error',
 max_depth = 8,
 max_features = None,
 max_leaf_nodes = None,
 min_impurity_decrease = 0.0,
 min_samples_leaf = 1,
 min_samples_split = 2,
 min_weight_fraction_leaf = 0.0,
 n_estimators = 500,
 n_iter_no_change = None,
 random_state = None,
 subsample = 0.2,
 tol = 0.0001,
 validation_fraction = 0.1,
 verbose = 0,
 warm_start = False)
grb_tunned.fit(train_features, train_labels)
gbr_tunned_pred = grb_tunned.predict(test_features)

In [ ]:
# Calculate the absolute errors
errors_gbr = abs(gbr_tunned_pred - test_labels)

# Print out the mean absolute error (mae)
r_sq = grb_tunned.score(test_features, test_labels)
print('Coeficiente de Determinação (R²):', r_sq)

print('MAE:', metrics.mean_absolute_error(test_labels, gbr_tunned_pred))
print('MSE:', metrics.mean_squared_error(test_labels, gbr_tunned_pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(test_labels, gbr_tunned_pred)))

Coeficiente de Determinação (R²): 0.9034980943932867
MAE: 0.02479545390024798
MSE: 0.00151294968763807
RMSE: 0.03889665393884248